# Generated by Django 5.1.7 on 2025-04-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
