[project]
name = "godtalk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.7",
    "django-allauth>=65.5.0",
    "django-browser-reload>=1.18.0",
]
